### ISSUE TITLE
Server crashes at 100.000 queries

### ISSUE THREAD

**Issue by toniSta** [toniSta/masterarbeit#1]
both servers (boost, no boost) crash as soon as the client sends more than a certain amount of queries. 100k is sufficient.

**Comment by toniSta** [comment]
Well this is Parser related:

```
#0  0x0000555556cd15fa in hsql_lex(HSQL_STYPE*, HSQL_CUST_LTYPE*, void*) ()
#1  0x0000555556ccd3b9 in hsql_parse(hsql::SQLParserResult*, void*)
    ()
#2  0x0000555556ccacc4 in hsql::SQLParser::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, hsql::SQLParserResult*) ()
#3  0x00005555562bd686 in opossum::SQLPipeline::SQLPipeline(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<opossum::TransactionContext>, opossum::UseMvcc, std::shared_ptr<opossum::LQPTranslator> const&, std::shared_ptr<opossum::Optimizer> const&, opossum::CleanupTemporaries) ()
#4  0x00005555562c2693 in opossum::SQLPipelineBuilder::create_pipeline() const ()
#5  0x00005555562b6bfe in create_pipeline(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x00005555562b8ea0 in Session::_handle_request() [clone .localalias.247] ()
#7  0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#8  0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#9  0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#10 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#11 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#12 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#13 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#14 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#15 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#16 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#17 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#18 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#19 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#20 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#21 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#22 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#23 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
#24 0x00005555562b8ded in Session::_handle_request() [clone .localalias.247] ()
```

**Comment by toniSta** [comment]
Parser was fixed
